[build]
builder = "nixpacks"
buildCommand = "npm run railway:build"
nixpacksPlan = """
[phases.setup]
nixPkgs = ['nodejs_20', 'postgresql']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run railway:build']
"""

[deploy]
startCommand = "npm run railway:start"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services]]
name = "web"
internalPort = 3000
protocol = "tcp"

[[services]]
name = "api"
internalPort = 5000
protocol = "tcp"